### ISSUE TITLE
Problem orchestrating tanks

### ISSUE THREAD

**Issue by thiagomatsuno** [uniquid/tank-java#1]
I'm having a problem orchestrating tanks compiled from this project.

When I create a tank from the command `./tank java start` I'm able to orchestrate it on the Orchestrator console (browser) after imprinting... but when I run a tank compiled from this project, the tank is announced, it appears on the list and is imprinted, but when I select it and click on Orchestrate button, I receive an error message on the status log, saying that the contract for XXXXX has failed.

The announce:

` {"name":"JTankRSXUG8C98CKW","xpub":"tpubDAY5Je7rzVCebmg3GaPLi6kgezQJ9dvEM6PWwwesW7n4A3E6728xNT5gnEdukbnvHiwEskT4a1gDkHFQpsFW8UxP6CbaS1Ne42VNehMADYy"}`

followed by

`2017-11-21 21:50:03Topic: JTankRSXUG8C98CKWQos: 1{"sender":"mteMRth2oL8iUcbeyBzs51o16sQ8MjB6sR","body":{"method":30,"id":1871431006,"params":"{\"tx\":\"010000000108f3f949f4071abd11282250cc9c4fc23f6844096d06e2d779fafb40314746ee000000004847304402207fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a002207fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a001ffffffff0410270000000000001976a914661f5b51bffe6523e91acd4fdbb84e9d57c7198988ac0000000000000000536a4c50000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030750000000000001976a914661f5b51bffe6523e91acd4fdbb84e9d57c7198988acf07e0e00000000001976a914e71a3f72f3a1705f8f0bda85610bb8027c8c98ff88ac00000000\",\"paths\":[\"0/0/0\"]}"}}`

Tank config file:

    networkParameters=com.uniquid.params.UniquidRegTest
    providerWalletFile=provider.wallet
    userWalletFile=user.wallet
    chainFile=chain.spvchain
    userChainFile=userchain.spvchain
    mqtt.broker=tcp://localhost:1883
    db.url=jdbc:sqlite:tank.db
    seedFile=seed.backup
    seedPassword=defaultpassword
    topic.announce=UID/announce
    bc.peers=127.0.0.1`

I attached the jar file to you to debug the application.

[Debug.zip](https://github.com/uniquid/tank-java/files/1491356/Debug.zip)

**Comment by gmagnotta** [comment]
Dear @thiagomatsuno, 

from the logs, I can see that your application is trying to contact the BlockChain Peer on 127.0.0.1, without success.

Maybe your idea was to connect to our infrastructure 52.225.217.168;52.167.211.151?

Regards,
Giuseppe

**Comment by thiagomatsuno** [comment]
Thanks for the reply.
You were right about the peer settings.

I was not able to orchestrate using the config. above. Instead, I found the config that the default tanks are using (`./tank java start`) and apply them on my project settings.

The only difference is the peer configs:

    // bc.peers=127.0.0.1 -> I had this
    // bc.peers=52.225.217.168;52.167.211.151 -> You gave me this, but failed (2 tries)
    bc.peers=52.225.217.168;52.167.211.151;52.225.218.133 //this worked

Why the default settings points the broker to your servers while the peers points to a local service? I think its complicated to understand.

Can you tell me where is this properties docs?

Thanks in advance

**Comment by gmagnotta** [comment]
Dear @thiagomatsuno,

The default config of the tank java requires that the user modify correctly the configuration. The 127.0.0.1 in the config is just a placeholder that forces the user to adjust the values to the proper environment he want to use. We want to avoid where possible cases where the user assumes to work in an environment while the system is working with other configurations.

So the 127.0.0.1 is not pointing to the broker, but it's pointing to a peer (port 19000) that in your case is missing on localhost.

Currently, the java library requires 3 blockchain peers to work correctly: 3 to be discovered, but 2 to be used each time.

The values I sent to you in previous communications are our blockchain regtest peers. There is another for backup pourposes (52.225.218.133).

If this satisfy your question, please close the issue.

Thank you

Best regards,
Giuseppe

**Comment by thiagomatsuno** [comment]
OK. Issue resolved.

Grazie (thanks)
