### ISSUE TITLE
Maven could not resolve some dependencies

### ISSUE THREAD

**Issue by mpiras** [uniquid/tank-java#2]
when launching
mvn clean package
gives the following error

[ERROR] Failed to execute goal on project tank-java: Could not resolve dependencies for project com.uniquid:tank-java:jar:0.1-RC1-SNAPSHOT: The following artifacts could not be resolved: org.gmagnotta:slf4j-jel:jar:0.1-SNAPSHOT, org.gmagnotta:java-embeddable-logger:jar:0.1-SNAPSHOT: Could not find artifact org.gmagnotta:slf4j-jel:jar:0.1-SNAPSHOT

It also gives two warnings

[WARNING] The POM for org.gmagnotta:slf4j-jel:jar:0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.gmagnotta:java-embeddable-logger:jar:0.1-SNAPSHOT is missing, no dependency information available

**Comment by gmagnotta** [comment]
Dear,

you need to download and build with the same approach (mvn clean package) the following two projects:

https://github.com/gmagnotta/JavaEmbeddableLogging

https://github.com/gmagnotta/slf4j-jel

Those are needed for logging purposes.

If you want, you can replace with any logging implementation that you prefer.

Regards,
Giuseppe
